version: "3.7"
services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --watch --force_polling --verbose -- livereload
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
